### ISSUE TITLE
HTTP 403 for rincewind_l4.06.1-0.9.1.exe

### ISSUE THREAD

**Issue by root-talis** [giraud/reasonml-idea-plugin#332]
plugin version: 0.98.3-2020.1

### Description
Whenever I type anything into a *.res file, I get the following popup:

```
Can't download /home/talis/.local/share/JetBrains/IntelliJIdea2020.1/reasonml-idea-plugin/rincewind_l4.06.1-0.9.1.exe java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/giraud/ocaml/rincewind_l4.06.1-0.9.1.exe
```

Also, I'm on Linux, so why download an *.exe? I can't test if it is working as intended, but probably this requires a separate issue.

**Comment by giraud** [comment]
This is normal, and there is nothing I can do.

The problem is that JFrog closed their bintray service and forced us to use artifactory.
It means that every plugin released before 0.100 (see [changelog](https://github.com/giraud/reasonml-idea-plugin/blob/master/CHANGELOG.md)) won't be able to download rincewind.
you need to use at least 0.100.

also, the binary is linux (l4.06 -> l is for linux, w is for windows and o is for mac). .exe is just an extension
